"""empty message

Revision ID: 22ea12a8631b
Revises: 
Create Date: 2024-06-13 12:55:34.089146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ea12a8631b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendname', sa.String(), nullable=True),
    sa.Column('friend_chating', sa.String(), nullable=True),
    sa.Column('my_chatting', sa.String(), nullable=True),
    sa.Column('chatting_time', sa.DateTime(), nullable=True),
    sa.Column('chatting_update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    # ### end Alembic commands ###
